namespace AgentServer.Structuring.Opcode
{
	public enum eShuProtocol
	{
		HATCH_REQ = 1,
		GET_CHARACTER_ITEM_LIST_ACK = 2,
		GET_ITEM_INFO_BY_STR_REQ = 3,
		BUY_ITEM_ACK = 3,
		GET_USER_ITEM_INFO_REQ = 5,
		GET_USER_STATUS_INFO_ACK = 8,
		MANAGER_ACTION_REQ = 9,
		CHANGE_NAME_REQ = 10,
		CHANGE_AVATAR_INFO_REQ = 11,
		CHANGE_CURRENT_SHU_REQ = 12,
		USE_ITEM_REQ = 13,
		GET_GIFT_REQ = 14,
		EXPLORE_CHECK_REQ = 15,
		EXPLORE_START_REQ = 16,
		EXPLORE_STOP_ACK = 17,
		EXPLORE_REWARD_ACK = 18,
		EXPLORE_STOP_REQ = 19,
		EXPLORE_REWARD_REQ = 20,
		LEVEL_UP_ACK = 20,
	}
}
