using System;

namespace AgentServer.Structuring.Opcode
{
	[Flags]
	public enum GuildPlantProtocol
	{
		GET_GUILD_MANAGE_TR_REQ = 0,
		GET_GUILD_MANAGE_TR_ACK = 1,
		GET_GUILD_MANAGE_TR_FAIL_ACK = 2,
		INVEST_GUILD_MANAGE_TR_REQ = 3,
		INVEST_GUILD_MANAGE_TR_ACK = 4,
		INVEST_GUILD_MANAGE_TR_FAIL_ACK = 5,
		GET_STORAGE_EXTEND_REQ = 6,
		GET_STORAGE_EXTEND_ACK = 7,
		GET_STORAGE_EXTEND_FAIL_ACK = 8,
		REGISTER_ITEM_REQ = 9,
		REGISTER_ITEM_ACK = 0xA,
		REGISTER_ITEM_FAIL_ACK = 0xB,
		GET_MAKE_PROGRESS_ITEM_REQ = 0xC,
		GET_MAKE_PROGRESS_ITEM_ACK = 0xD,
		GET_MAKE_PROGRESS_ITEM_FAIL_ACK = 0xE,
		GET_MAKE_STAND_BY_ITEM_LIST_REQ = 0x10,
		GET_MAKE_STAND_BY_ITEM_LIST_ACK = 0x11,
		GET_MAKE_STAND_BY_ITEM_LIST_FAIL_ACK = 0x12,
		CHANGE_MY_CONSTRIBUTION_POINT_ITEM_REQ = 0x13,
		CHANGE_MY_CONSTRIBUTION_POINT_ITEM_ACK = 0x14,
		CHANGE_MY_CONSTRIBUTION_POINT_ITEM_FAIL_ACK = 0x15,
		GET_INVESTOR_MANAGE_TR_LIST_REQ = 0x16,
		GET_INVESTOR_MANAGE_TR_LIST_ACK = 0x17,
		GET_INVESTOR_MANAGE_TR_LIST_FAIL_ACK = 0x18,
		GET_EXPENSE_LIST_REQ = 0x19,
		GET_EXPENSE_LIST_ACK = 0x1A,
		GET_EXPENSE_LIST_FAIL_ACK = 0x1B,
		GET_ITEM_CONTRIBUTION_RANK_LIST_REQ = 0x1C,
		GET_ITEM_CONTRIBUTION_RANK_LIST_ACK = 0x1D,
		GET_ITEM_CONTRIBUTION_RANK_LIST_FAIL_ACK = 0x1E,
		GET_GIVE_POSSIBLE_USER_LIST_REQ = 0x1F,
		GET_GIVE_POSSIBLE_USER_LIST_ACK = 0x20,
		GET_GIVE_POSSIBLE_USER_LIST_FAIL_ACK = 0x21,
		GIVE_GIFT_REQ = 0x22,
		GIVE_GIFT_ACK = 0x23,
		GIVE_GIFT_FAIL_ACK = 0x24,
		GET_PLANT_ITEM_LIST_REQ = 0x25,
		GET_PLANT_ITEM_LIST_ACK = 0x26,
		GET_PLANT_ITEM_LIST_FAIL_ACK = 0x27,
		BUY_ITEM_REQ = 0x28,
		BUY_ITEM_ACK = 0x29,
		BUY_ITEM_FAIL_ACK = 0x2A
	}
}
