namespace TRCommon
{
	public enum ITEM_POSITION
	{
		ITEM_POSITION_CHARACTER,
		ITEM_POSITION_HEAD,
		ITEM_POSITION_TOPBODY,
		ITEM_POSITION_DOWNBODY,
		ITEM_POSITION_FOOT,
		ITEM_POSITION_ACCHEAD,
		ITEM_POSITION_ACCFACE,
		ITEM_POSITION_ACCHAND,
		ITEM_POSITION_ACCBACK,
		ITEM_POSITION_ACCNECK,
		ITEM_POSITION_PET,
		ITEM_POSITION_EXPANSION,
		ITEM_POSITION_ACCWRIST,
		ITEM_POSITION_ACCBOOSTER,
		ITEM_POSITION_ACCTAIL,
		ITEM_POSITION_COUNT
	}
}
