namespace TRCommon
{
	public enum ITEM_POSITION_GACC
	{
		ITEM_POSITION_GACC_HEAD,
		ITEM_POSITION_GACC_HAND,
		ITEM_POSITION_GACC_FOOT,
		ITEM_POSITION_GACC_TOPBODY,
		ITEM_POSITION_GACC_POSE,
		ITEM_POSITION_GACC_BACK,
		ITEM_POSITION_GACC_EVENT,
		ITEM_POSITION_GACC_COUNT
	}
}
