using System;

namespace RoomServer.Structuring.Opcode
{
	[Flags]
	public enum FarmProtocol
	{
		EnterFarm_REQ = 0,
		CreatePublicFarm_REQ = 1,
		GetFarmPoint_REQ = 0xA,
		GetFarmPoint_ACK = 0xB,
		PublicFarmList_REQ = 0xC,
		PieroFarmList_REQ = 0xE,
		PublicFarmList_ACK = 0xF,
		CreateFarm_ACK = 0x11,
		GetMyFarmInfo_REQ = 0x16,
		GetMyFarmInfo_ACK = 0x17,
		EnterGuildFarm_REQ = 0x18,
		GetGuildFarmInfo_REQ = 0x19,
		GetGuildFarmInfo_ACK = 0x1A,
		GetGuildFarmObjectAttr_REQ = 0x1B,
		GetGuildFarmObjectAttr_ACK = 0x1C,
		ModifyGuildFarmNoticeBoardInfo_REQ = 0x1D,
		ModifyGuildFarmNoticeBoardInfo_ACK = 0x1E,
		GetGuildFarmItemList_REQ = 0x20,
		GetGuildFarmItemList_ACK = 0x21,
		GetMyFarmItemList_REQ = 0x26,
		GetMyFarmItemList_ACK_1 = 0x27,
		GetMyFarmItemList_ACK_2 = 0x28,
		GetMyFarmItemList_ACK_3 = 0x29,
		GetFarmItemList_REQ = 0x2A,
		GetFarmItemList_ACK = 0x2B,
		FarmItemAttr_REQ = 0x2D,
		FarmItemAttr_ACK = 0x2E,
		ReloadFarmMapInfo_REQ = 0x31,
		ReloadFarmMapInfo_ACK_1 = 0x32,
		ReloadFarmMapInfo_ACK_2 = 0x33,
		ReloadFarmMapInfo_ACK_3 = 0x34,
		FarmProtocol_UNK1_REQ = 0x35,
		FarmProtocol_UNK1_ACK = 0x36,
		ChangeFarmMapTypeBySlot_UpdateItem = 0x37,
		ChangeFarmMapTypeBySlot_UpdateInfo = 0x38,
		ClearUserFarmMapInfo_REQ = 0x3C,
		ClearUserFarmMapInfo_ACK = 0x3D,
		ModifyFarmMapInfo_REQ = 0x3E,
		ModifyFarmMapInfo_ACK = 0x3F,
		SearchFarm_REQ = 0x43,
		SearchFarm_ACK = 0x44,
		SearchFarmByUserNum_REQ = 0x45,
		SearchFarmByUserNum_ACK = 0x46,
		JoinFarmRoom_REQ = 0x55,
		IncreaseAnimalSize_REQ = 0x5F,
		IncreaseAnimalSize_ACK = 0x60,
		RestoreAnimalDefaultSize_REQ = 0x61,
		RestoreAnimalDefaultSize_ACK = 0x62,
		ChangeFarmType_REQ = 0x63,
		ChangeFarmMapTypeByItem_ACK = 0x64,
		ModifyObjectValueInfo_REQ = 0x68,
		ModifyObjectValueInfo_ACK = 0x69,
		ChangeFarmSkybox_REQ = 0x6B,
		ChangeFarmSkybox_ACK = 0x6C,
		Expired_farm_item_REQ = 0x6D,
		Expired_farm_item_ACK = 0x6E,
		ChangeFarmWeather_REQ = 0x6F,
		ChangeFarmWeather_ACK = 0x70,
		GetMasterUserInfo_REQ = 0x71,
		GetMasterUserInfo_ACK = 0x74,
		GetMasterUserInfo_REQ_KR = 0x73,
		FarmProtocol_UNK2_REQ = 0x7C,
		FarmProtocol_UNK2_ACK = 0x7D,
		SetFarmPortalInfo_REQ = 0x7F,
		SetFarmPortalInfo_ACK = 0x80,
		GetFarmPortalInfo_REQ = 0x82,
		GetFarmPortalInfo_ACK = 0x83,
		GetFarmSlotListInfo_REQ = 0x88,
		GetFarmSlotListInfo_ACK = 0x89,
		SaveUserFarmSlotInfo_ACK = 0x8B,
		ClearFarmSlotInfo_REQ = 0x8C,
		ClearFarmSlotInfo_ACK = 0x8D,
		ChangeFarmMapTypeBySlot_REQ = 0x8E,
		ChangeFarmMapTypeBySlot_ACK = 0x8F,
		BuyFarmSlot_ACK = 0x90
	}
}
